// <auto-generated />
namespace SpaceShipShop.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DataContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201310011634242_DataContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
