// <auto-generated />
namespace SpaceShipShop.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PreCss : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PreCss));
        
        string IMigrationMetadata.Id
        {
            get { return "201310081730055_PreCss"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
